import { TOPIC_MEDIA } from "@/config/media";
import { ROUTES } from "@/config/routes";
import { SITE } from "@/config/site";
import type { ContentPage } from "@/types/content";

export const FAQ_PAGE: ContentPage = {
  id: "faq",
  order: 6,
  numberLabel: "06",
  slug: "골반필러-자주묻는질문",
  href: ROUTES.faq,
  navLabel: "FAQ",
  categoryLabel: SITE.categoryLabel,
  h1: "골반필러에 대해 자주 묻는 질문은 무엇일까요?",
  heading: "골반필러에 대해 자주 묻는 질문은 무엇일까요?",
  intro: [
    "골반필러 FAQ는 가격, 통증, 주입량, 앉기와 운전, 운동, 붓기, 유지기간, 제거 가능성, 병원선택처럼 자주 이어지는 질문을 정리한 페이지입니다.",
    "각 답변은 제품, 시술 방법, 개인 상태에 따라 달라질 수 있다는 점을 전제로 읽는 편이 좋습니다.",
  ],
  publishedAt: "2026-07-28",
  updatedAt: "2026-07-28",
  faqIds: [
    "main-01",
    "main-02",
    "main-03",
    "main-04",
    "main-05",
    "main-06",
    "main-07",
    "main-08",
    "main-09",
    "main-10",
    "faq-11",
    "faq-12",
    "faq-13",
    "faq-14",
  ],
  faqTitle: "골반필러 자주 묻는 질문",
  conclusion: [
    "FAQ는 공통적으로 궁금한 범위를 정리한 내용이므로, 실제 적용 여부와 시점은 제품과 개인 상태에 따라 달라질 수 있습니다.",
    "가격과 후기, 주의사항, 병원선택, 유지 및 회복기간 페이지를 함께 보면 질문을 더 구체적으로 정리하기 좋습니다.",
  ],
  thumbnail: TOPIC_MEDIA.faq.thumbnail,
  topImages: [TOPIC_MEDIA.faq.thumbnail],
  bodyImage: TOPIC_MEDIA.faq.secondaryImage,
  heroImage: TOPIC_MEDIA.faq.thumbnail,
  secondaryImage: TOPIC_MEDIA.faq.secondaryImage,
  repeatImage: null,
  inlineImage: TOPIC_MEDIA.faq.secondaryImage,
  accentColor: TOPIC_MEDIA.faq.accentColor,
  accentHoverColor: TOPIC_MEDIA.faq.accentHoverColor,
  showArticleEyebrow: false,
  showRelatedGuideHeading: false,
  showContentCards: true,
  showFaqHub: true,
  repeatImageBeforeSectionNumber: null,
  keySummary: [
    { numberLabel: "01", title: "가격", text: "제품과 용량, 범위에 따라 달라질 수 있습니다." },
    { numberLabel: "02", title: "통증과 붓기", text: "제품과 방법, 개인 상태에 따라 체감이 다를 수 있습니다." },
    { numberLabel: "03", title: "운동과 회복", text: "활동 재개는 의료진 안내를 우선합니다." },
    { numberLabel: "04", title: "제거와 병원선택", text: "제거 가능성과 대응 체계는 상담에서 확인해야 합니다." },
  ],
  seo: {
    title: "골반필러에 대해 자주 묻는 질문은 무엇일까요? | 필러가이드",
    description: "골반필러 가격, 통증, 붓기, 운동, 앉기, 유지기간, 필러 제거와 병원선택에 관한 자주 묻는 질문을 정리합니다.",
    keywords: ["골반필러 FAQ", "골반필러 자주 묻는 질문", "골반필러 제거"],
    ogImage: TOPIC_MEDIA.faq.thumbnail.src,
    socialImage: TOPIC_MEDIA.faq.thumbnail.src,
    category: SITE.categoryLabel,
  },
  sections: [
    {
      id: "faq-price",
      order: 1,
      numberLabel: "01",
      heading: "가격과 주입량 관련 질문",
      layout: "checklist",
      directAnswer:
        "가격과 주입량은 제품, 성분, 예상 용량, 범위와 사후관리 구성에 따라 달라질 수 있으므로 총액만으로 판단하기 어렵습니다.",
      paragraphs: ["자세한 비용 기준은 골반필러 가격 및 비용 페이지를 함께 확인하는 편이 좋습니다."],
      bullets: [
        "양쪽 합산 용량인지",
        "제품명과 성분 설명이 있는지",
        "사후관리 포함 여부",
        "추가 비용 조건",
      ],
      relatedHref: ROUTES.cost,
      relatedLabel: "골반필러 가격 및 비용 보기",
    },
    {
      id: "faq-recovery",
      order: 2,
      numberLabel: "02",
      heading: "통증, 붓기, 운동과 회복 관련 질문",
      layout: "timeline",
      directAnswer:
        "통증과 붓기, 운동 재개 시점은 제품과 개인 상태, 시술 범위에 따라 다를 수 있어 단계적으로 확인하는 편이 좋습니다.",
      paragraphs: ["회복 흐름은 시술 직후, 초기 회복, 경과 관찰, 형태 평가 시점으로 나눠 이해하면 도움이 됩니다."],
      timeline: [
        { label: "시술 직후", text: "붓기와 압통, 촉감 변화를 관찰합니다." },
        { label: "초기 회복", text: "운동과 열 자극, 압박을 조절합니다." },
        { label: "경과 관찰", text: "부기 변화와 눌림감을 비교합니다." },
        { label: "형태 평가", text: "안정화 이후 다시 확인합니다." },
      ],
      relatedHref: ROUTES.recovery,
      relatedLabel: "골반필러 유지 및 회복기간 보기",
    },
    {
      id: "faq-safety",
      order: 3,
      numberLabel: "03",
      heading: "주의사항과 이상 반응 관련 질문",
      layout: "comparison",
      directAnswer:
        "일반적으로 나타날 수 있는 반응과 빠르게 확인이 필요한 이상 징후를 구분해서 안내받는 것이 중요합니다.",
      paragraphs: ["시술 전후 주의사항과 부작용 기준은 별도 페이지에서 더 자세히 볼 수 있습니다."],
      comparison: {
        left: { label: "일반 반응", text: "멍, 붓기, 압통, 촉감 변화가 일정 기간 느껴질 수 있습니다." },
        right: { label: "빠른 확인 필요", text: "심한 통증, 열감, 피부 색 변화, 급격한 부기 악화는 진료가 필요할 수 있습니다." },
      },
      relatedHref: ROUTES.precautions,
      relatedLabel: "골반필러 주의사항 보기",
    },
    {
      id: "faq-clinic",
      order: 4,
      numberLabel: "04",
      heading: "병원선택과 후기 관련 질문",
      layout: "info-grid",
      directAnswer:
        "병원선택과 후기 확인에서는 제품 정보, 설명 체계, 촬영 시점, 보정 여부, 사후 대응 경험을 함께 보는 편이 좋습니다.",
      paragraphs: ["후기만으로 결정하기보다 제품과 계획을 직접 설명하는지 확인하는 과정이 중요합니다."],
      infoBlocks: [
        { label: "제품 정보", text: "허가사항과 성분 설명 여부" },
        { label: "주입 계획", text: "예상 용량과 범위 설명 여부" },
        { label: "후기 읽기", text: "촬영 시점과 보정 여부 확인" },
        { label: "사후 대응", text: "이상 반응 시 대응 체계 확인" },
      ],
      relatedHref: ROUTES.hospital,
      relatedLabel: "골반필러 병원선택 보기",
    },
  ],
};
